# Generated by Django 4.1.2 on 2022-11-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
                ('auther', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
