# Generated by Django 4.1.2 on 2022-11-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='books',
            new_name='bookname',
        ),
    ]
